version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: control-panel-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    networks:
      - app-network

  # Backend API service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: control-panel-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD:-password}@mongo:27017/control-panel?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_here}
      JWT_EXPIRE: ${JWT_EXPIRE:-30d}
    networks:
      - app-network

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: control-panel-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:5000/api
    networks:
      - app-network

# Volumes
volumes:
  mongo-data:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge 